### ISSUE TITLE
[Design]RegisterPhrase UI 구현

### ISSUE THREAD

**Issue by morningfest** [DeveloperAcademy-POSTECH/2024-MC3-A17-ApplePuffGirls#20]
## 🛠 Issue

문구 추가하기 단계 뷰를 만들어야합니다.
## 📝 To-do

- [x] progressbar 공부하기
- [x] 문구 추가하기뷰 짜기
- [x] 감상평 추가하기뷰 짜기

**Comment by Guryss** [comment]
김리 주무세요.
