### ISSUE TITLE
[Design] Custom NavigationBar로 교체가 아니고 빵수증 제작하기

### ISSUE THREAD

**Issue by 3405000** [DeveloperAcademy-POSTECH/2024-MC3-A17-ApplePuffGirls#35]
## 🛠 Issue

구리스가 아직 네비게이션바 안 올림 이슈로 일단 빵수증부터 하기

## 📝 To-do

- [x] 구리스가 만든 네비게이션바로 일괄 교체합니도
- [x] 김리가 요청한 PhraseCard 간격 수정하기를 합니도

**Comment by Guryss** [comment]
빵수증 내일까지 완료해서 올리세요
