### ISSUE TITLE
[Fix] 클립 데이터 연결

### ISSUE THREAD

**Issue by 3405000** [DeveloperAcademy-POSTECH/2024-MC3-A17-ApplePuffGirls#58]
## 🛠 Issue

클립 데이터를 연결합니다.

## 📝 To-do

- [x] 클립 데이터 연결해서 클립 추가하기를 하면 클립 리스트에 떠야 합니당

**Comment by 3405000** [comment]
클립 수정하기도 연결하려고 했는데 그거 하려면 너무 크게 뒤집어야 해서 일단 흐린눈 하겠습니다 ..

**Comment by 3405000** [comment]
클립 리스트, 상세뷰에서 구절 갯수 보이게 했는데… 근데 빌드해서 시뮬레이터로 봤을 때 저는 새 책 추가가 안되어요 그래서 잘 연결 되었는지는 모르겠어용

**Comment by Guryss** [comment]
금일 샤따 확인했습니다. 내일 샤따 잘 올려주시길. 수고 많았습니다. 쩨리쩨리.
